import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 sm:px-8 lg:px-12 py-16">
        <Link href="/" className="text-vision-navy hover:text-vision-dark font-text mb-8 inline-block">
          ← Back to home
        </Link>
        
        <h1 className="text-4xl font-display font-bold text-vision-dark mb-8">
          Terms of Use
        </h1>
        
        <div className="prose prose-lg max-w-none font-text text-vision-navy">
          <p className="text-lg mb-6">
            <strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
          
          <section className="mb-8">
            <h2 className="text-2xl font-display font-bold text-vision-dark mb-4">
              Acceptance of Terms
            </h2>
            <p className="mb-4">
              By downloading and using VisionBoard AI, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the app.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-2xl font-display font-bold text-vision-dark mb-4">
              Use of the App
            </h2>
            <p className="mb-4">
              VisionBoard AI is provided for personal use. You may use the app to create goals, track progress, and reflect on your journey. The app is designed to be a supportive tool for personal development.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-2xl font-display font-bold text-vision-dark mb-4">
              AI-Generated Content
            </h2>
            <p className="mb-4">
              Goals and affirmations generated by the AI are suggestions based on your input. You are responsible for reviewing and adapting these suggestions to fit your personal circumstances and values.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-2xl font-display font-bold text-vision-dark mb-4">
              Limitation of Liability
            </h2>
            <p className="mb-4">
              VisionBoard AI is provided "as is" without warranties of any kind. We are not responsible for any outcomes resulting from the use of the app or AI-generated content.
            </p>
          </section>
          
          <section className="mb-8">
            <h2 className="text-2xl font-display font-bold text-vision-dark mb-4">
              Changes to Terms
            </h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}

